"""Replay adapter for previously recorded agent choices.

This module is experimental instrumentation. It never selects a next action and
must not be used as an incident coordinator. A fixture is an immutable recording
of choices made by an agent, replayed only to make offline evaluation repeatable.
"""

from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime, timedelta
from typing import Self
from uuid import NAMESPACE_URL, UUID, uuid5

from pydantic import BaseModel, ConfigDict, Field, JsonValue, model_validator

from vital_relay.agent.capabilities import ToolInvocationContext
from vital_relay.agent.contracts import (
    AgentConclusion,
    AgentFailureCode,
    AgentRunRequest,
    AgentRunResult,
    AgentRunStatus,
    SandboxKind,
    VLLMSettings,
)
from vital_relay.agent.deep_agent import (
    AgentRuntimeUnavailableError,
    DeepAgentRunner,
)
from vital_relay.agent.policy import CoordinationPolicySnapshot
from vital_relay.agent.tools import (
    BoundedToolGateway,
    RuntimeTool,
    ToolGatewayError,
    ToolGatewayErrorCode,
)
from vital_relay.evolution.ace.contracts import SelectedContext
from vital_relay.evolution.contracts import CandidateManifest, EvaluationReport
from vital_relay.evolution.hashing import canonical_json_bytes


class RecordedModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class RecordedAgentAction(RecordedModel):
    tool_name: str = Field(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    arguments: dict[str, JsonValue]
    started_offset_seconds: float = Field(ge=0, le=3_600)
    finished_offset_seconds: float = Field(ge=0, le=3_600)
    expected_result: JsonValue | None = None
    expected_error_code: ToolGatewayErrorCode | None = None

    @model_validator(mode="after")
    def validate_timing_and_outcome(self) -> Self:
        if self.finished_offset_seconds < self.started_offset_seconds:
            raise ValueError("recorded action cannot finish before it starts")
        if self.expected_error_code is not None and self.expected_result is not None:
            raise ValueError("failed actions cannot include an expected result")
        return self


class RecordedAgentFixture(RecordedModel):
    fixture_id: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,95}$")
    model_id: str = Field(min_length=1, max_length=200)
    sandbox: SandboxKind = SandboxKind.IN_PROCESS
    status: AgentRunStatus
    actions: tuple[RecordedAgentAction, ...] = ()
    conclusion: AgentConclusion | None = None
    failure_code: AgentFailureCode | None = None
    finished_offset_seconds: float = Field(ge=0, le=3_600)

    @model_validator(mode="after")
    def validate_outcome(self) -> Self:
        latest_action = max(
            (action.finished_offset_seconds for action in self.actions),
            default=0,
        )
        if self.finished_offset_seconds < latest_action:
            raise ValueError("fixture must finish after every recorded action")
        if self.status is AgentRunStatus.COMPLETED:
            if self.conclusion is None or self.failure_code is not None:
                raise ValueError("completed recordings require only a conclusion")
            if any(action.expected_error_code is not None for action in self.actions):
                raise ValueError("completed recordings cannot contain tool failures")
        elif self.conclusion is not None or self.failure_code is None:
            raise ValueError("manual recordings require only a failure code")
        return self


class RecordedEvaluationFixture(RecordedModel):
    """Pinned baseline evidence regenerated by the repeatability test."""

    fixture_id: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,95}$")
    scenario_case_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    candidate: CandidateManifest
    agent: RecordedAgentFixture
    expected_report: EvaluationReport

    @model_validator(mode="after")
    def validate_identity(self) -> Self:
        if self.expected_report.candidate_sha256 != self.candidate.candidate_sha256:
            raise ValueError("recorded report belongs to a different candidate")
        return self


class RecordedAgentRunner:
    """Replay choices through the production A2 runner and dispatcher path."""

    def __init__(self, fixture: RecordedAgentFixture) -> None:
        self._fixture = fixture

    def run(
        self,
        request: AgentRunRequest,
        tools: BoundedToolGateway,
        *,
        policy_snapshot: CoordinationPolicySnapshot,
        invocation_context: ToolInvocationContext,
        selected_context: SelectedContext,
    ) -> AgentRunResult:
        clock = _SequenceClock(
            (
                request.requested_at,
                *(
                    timestamp
                    for action in self._fixture.actions
                    for timestamp in (
                        request.requested_at
                        + timedelta(seconds=action.started_offset_seconds),
                        request.requested_at
                        + timedelta(seconds=action.finished_offset_seconds),
                    )
                ),
                request.requested_at
                + timedelta(seconds=self._fixture.finished_offset_seconds),
            )
        )
        result = DeepAgentRunner(
            VLLMSettings(model=self._fixture.model_id),
            factory=_RecordedFactory(self._fixture),
            clock=clock,
            identifier_factory=_RecordedIdentifierFactory(request.run_id),
            sandbox=self._fixture.sandbox,
        ).run(
            request,
            tools,
            policy_snapshot=policy_snapshot,
            invocation_context=invocation_context,
            selected_context=selected_context,
        )
        if (
            result.status is not self._fixture.status
            or result.failure_code is not self._fixture.failure_code
            or result.conclusion != self._fixture.conclusion
        ):
            raise ValueError("recorded outcome no longer matches the production runner")
        return result


class _RecordedFactory:
    def __init__(self, fixture: RecordedAgentFixture) -> None:
        self._fixture = fixture

    def create(
        self,
        settings: VLLMSettings,
        runtime_tools: tuple[RuntimeTool, ...],
        *,
        system_prompt: str,
    ) -> _RecordedInvoker:
        del settings, system_prompt
        return _RecordedInvoker(self._fixture, runtime_tools)


class _RecordedInvoker:
    def __init__(
        self,
        fixture: RecordedAgentFixture,
        runtime_tools: tuple[RuntimeTool, ...],
    ) -> None:
        self._fixture = fixture
        self._tools = {tool.definition.name: tool for tool in runtime_tools}

    def invoke(self, value: Mapping[str, object]) -> Mapping[str, object]:
        del value
        for action in self._fixture.actions:
            tool = self._tools.get(action.tool_name)
            if tool is None:
                raise ValueError("recording references a state-disallowed tool")
            try:
                result = tool.invoke(action.arguments)
            except ToolGatewayError as exc:
                if action.expected_error_code is not exc.code:
                    raise ValueError(
                        "recorded tool error no longer matches world"
                    ) from exc
            else:
                if action.expected_error_code is not None:
                    raise ValueError("recorded tool failure unexpectedly succeeded")
                if canonical_json_bytes(result) != canonical_json_bytes(
                    action.expected_result
                ):
                    raise ValueError("recorded tool result no longer matches world")
        if self._fixture.failure_code in {
            AgentFailureCode.MODEL_TIMEOUT,
            AgentFailureCode.MODEL_UNAVAILABLE,
            AgentFailureCode.RUNNER_ERROR,
        }:
            _raise_recorded_runtime_failure(self._fixture.failure_code)
        if self._fixture.failure_code is AgentFailureCode.INVALID_MODEL_OUTPUT:
            return {}
        if self._fixture.failure_code is AgentFailureCode.AGENT_REQUESTED_HUMAN:
            return {
                "structured_response": AgentConclusion(
                    action_summary="Recorded agent requested human review.",
                    requires_human_review=True,
                )
            }
        return {"structured_response": self._fixture.conclusion}


class _SequenceClock:
    def __init__(self, values: tuple[datetime, ...]) -> None:
        self._values = iter(values)
        self._last = values[-1]

    def now(self) -> datetime:
        self._last = next(self._values, self._last)
        return self._last


class _RecordedIdentifierFactory:
    def __init__(self, run_id: UUID) -> None:
        self._run_id = run_id
        self._ordinal = 0

    def __call__(self) -> UUID:
        self._ordinal += 1
        return uuid5(
            NAMESPACE_URL,
            f"vital-relay:recorded-tool-call:{self._run_id}:{self._ordinal}",
        )


def _raise_recorded_runtime_failure(failure: AgentFailureCode) -> None:
    if failure is AgentFailureCode.MODEL_TIMEOUT:
        raise TimeoutError("recorded model timeout")
    if failure is AgentFailureCode.MODEL_UNAVAILABLE:
        raise AgentRuntimeUnavailableError("recorded model unavailable")
    if failure is AgentFailureCode.RUNNER_ERROR:
        raise RuntimeError("recorded runner error")
